from typing import Final

pokemon_stats: Final[dict[str, dict[str, tuple[str, ...] | int]]] = {
    "Articuno": {
        "hp": 90,
        "atk": 85,
        "def": 100,
        "sp.atk": 95,
        "sp.def": 125,
        "speed": 85,
        "types": ("ice", "flying")
    },
    "Blaziken": {
        "hp": 80,
        "atk": 120,
        "def": 70,
        "sp.atk": 110,
        "sp.def": 70,
        "speed": 80,
        "types": ("fire", "fighting")
    },
    "Charizard": {
        "hp": 78,
        "atk": 84,
        "def": 78,
        "sp.atk": 109,
        "sp.def": 85,
        "speed": 100,
        "types": ("fire", "flying")
    },
    "Dragonite": {
        "hp": 91,
        "atk": 134,
        "def": 95,
        "sp.atk": 100,
        "sp.def": 100,
        "speed": 80,
        "types": ("dragon", "flying")
    },
    "Gardevoir": {
        "hp": 68,
        "atk": 65,
        "def": 65,
        "sp.atk": 125,
        "sp.def": 115,
        "speed": 80,
        "types": ("psychic", "fairy")
    },
    "Gengar": {
        "hp": 60,
        "atk": 65,
        "def": 60,
        "sp.atk": 130,
        "sp.def": 75,
        "speed": 110,
        "types": ("ghost", "poison")
    },
    "Groudon": {
        "hp": 100,
        "atk": 150,
        "def": 140,
        "sp.atk": 100,
        "sp.def": 90,
        "speed": 90,
        "types": ("ground",)
    },
    "Gyarados": {
        "hp": 95,
        "atk": 125,
        "def": 79,
        "sp.atk": 60,
        "sp.def": 100,
        "speed": 81,
        "types": ("water", "flying")
    },
    "Kyogre": {
        "hp": 100,
        "atk": 100,
        "def": 90,
        "sp.atk": 150,
        "sp.def": 140,
        "speed": 90,
        "types": ("water",)
    },
    "Lapras": {
        "hp": 130,
        "atk": 85,
        "def": 80,
        "sp.atk": 85,
        "sp.def": 95,
        "speed": 60,
        "types": ("water", "ice")
    },
    "Lucario": {
        "hp": 70,
        "atk": 110,
        "def": 70,
        "sp.atk": 115,
        "sp.def": 70,
        "speed": 90,
        "types": ("fighting", "steel")
    },
    "Lugia": {
        "hp": 106,
        "atk": 90,
        "def": 130,
        "sp.atk": 90,
        "sp.def": 154,
        "speed": 110,
        "types": ("psychic", "flying")
    },
    "Machamp": {
        "hp": 90,
        "atk": 130,
        "def": 80,
        "sp.atk": 65,
        "sp.def": 85,
        "speed": 55,
        "types": ("fighting",)
    },
    "Mew": {
        "hp": 100,
        "atk": 100,
        "def": 100,
        "sp.atk": 100,
        "sp.def": 100,
        "speed": 100,
        "types": ("psychic",)
    },
    "Mewtwo": {
        "hp": 106,
        "atk": 110,
        "def": 90,
        "sp.atk": 154,
        "sp.def": 90,
        "speed": 130,
        "types": ("psychic",)
    },
    "Moltres": {
        "hp": 90,
        "atk": 100,
        "def": 90,
        "sp.atk": 100,
        "sp.def": 125,
        "speed": 90,
        "types": ("fire", "flying")
    },
    "Pikachu": {
        "hp": 45,
        "atk": 80,
        "def": 50,
        "sp.atk": 75,
        "sp.def": 60,
        "speed": 120,
        "types": ("electric",)
    },
    "Rayquaza": {
        "hp": 105,
        "atk": 150,
        "def": 90,
        "sp.atk": 150,
        "sp.def": 90,
        "speed": 95,
        "types": ("dragon", "flyng")
    },
    "Sceptile": {
        "hp": 70,
        "atk": 85,
        "def": 65,
        "sp.atk": 105,
        "sp.def": 85,
        "speed": 120,
        "types": ("grass",)
    },
    "Swampert": {
        "hp": 100,
        "atk": 110,
        "def": 90,
        "sp.atk": 85,
        "sp.def": 90,
        "speed": 60,
        "types": ("water", "ground")
    },
    "Zapdos": {
        "hp": 90,
        "atk": 90,
        "def": 85,
        "sp.atk": 125,
        "sp.def": 90,
        "speed": 100,
        "types": ("electric", "flying")
    }
}

types_efficiency_on_attack: Final[dict[str, dict[str, int]]] = {
    'normal': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 1,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 0.5,
        'ghost': 0,
        'dragon': 1,
        'dark': 1,
        'steel': 0.5,
        'fairy': 1,
    },
    'fire': {
        'normal': 1,
        'fire': 0.5,
        'water': 0.5,
        'electric': 1,
        'grass': 2,
        'ice': 2,
        'fighting': 1,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 2,
        'rock': 0.5,
        'ghost': 1,
        'dragon': 0.5,
        'dark': 1,
        'steel': 2,
        'fairy': 1,
    },
    'water': {
        'normal': 1,
        'fire': 1,
        'water': 0.5,
        'electric': 1,
        'grass': 0.5,
        'ice': 1,
        'fighting': 1,
        'poison': 1,
        'ground': 2,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 2,
        'ghost': 1,
        'dragon': 0.5,
        'dark': 1,
        'steel': 1,
        'fairy': 1,
    },
    'electric': {
        'normal': 1,
        'fire': 1,
        'water': 2,
        'electric': 0.5,
        'grass': 0.5,
        'ice': 1,
        'fighting': 1,
        'poison': 1,
        'ground': 0,
        'flying': 2,
        'psychic': 1,
        'bug': 1,
        'rock': 1,
        'ghost': 1,
        'dragon': 0.5,
        'dark': 1,
        'steel': 1,
        'fairy': 1,
    },
    'grass': {
        'normal': 1,
        'fire': 0.5,
        'water': 2,
        'electric': 1,
        'grass': 0.5,
        'ice': 1,
        'fighting': 1,
        'poison': 0.5,
        'ground': 2,
        'flying': 0.5,
        'psychic': 1,
        'bug': 0.5,
        'rock': 2,
        'ghost': 1,
        'dragon': 0.5,
        'dark': 1,
        'steel': 0.5,
        'fairy': 1,
    },
    'ice': {
        'normal': 1,
        'fire': 0.5,
        'water': 0.5,
        'electric': 1,
        'grass': 2,
        'ice': 0.5,
        'fighting': 1,
        'poison': 1,
        'ground': 2,
        'flying': 2,
        'psychic': 1,
        'bug': 1,
        'rock': 1,
        'ghost': 1,
        'dragon': 2,
        'dark': 1,
        'steel': 0.5,
        'fairy': 1,
    },
    'fighting': {
        'normal': 2,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 2,
        'fighting': 1,
        'poison': 0.5,
        'ground': 1,
        'flying': 0.5,
        'psychic': 0.5,
        'bug': 0.5,
        'rock': 2,
        'ghost': 0,
        'dragon': 1,
        'dark': 2,
        'steel': 2,
        'fairy': 0.5,
    },
    'poison': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 2,
        'ice': 1,
        'fighting': 1,
        'poison': 0.5,
        'ground': 0.5,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 0.5,
        'ghost': 0.5,
        'dragon': 1,
        'dark': 1,
        'steel': 0,
        'fairy': 2,
    },
    'ground': {
        'normal': 1,
        'fire': 2,
        'water': 1,
        'electric': 2,
        'grass': 0.5,
        'ice': 1,
        'fighting': 1,
        'poison': 2,
        'ground': 1,
        'flying': 0,
        'psychic': 1,
        'bug': 0.5,
        'rock': 2,
        'ghost': 1,
        'dragon': 1,
        'dark': 1,
        'steel': 2,
        'fairy': 0,
    },
    'flying': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 0.5,
        'grass': 2,
        'ice': 1,
        'fighting': 2,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 2,
        'rock': 0.5,
        'ghost': 1,
        'dragon': 1,
        'dark': 1,
        'steel': 0.5,
        'fairy': 1,
    },
    'psychic': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 2,
        'poison': 2,
        'ground': 1,
        'flying': 1,
        'psychic': 0.5,
        'bug': 1,
        'rock': 1,
        'ghost': 1,
        'dragon': 1,
        'dark': 0,
        'steel': 0.5,
        'fairy': 1,
    },
    'bug': {
        'normal': 1,
        'fire': 0.5,
        'water': 1,
        'electric': 1,
        'grass': 2,
        'ice': 1,
        'fighting': 0.5,
        'poison': 0.5,
        'ground': 1,
        'flying': 0.5,
        'psychic': 2,
        'bug': 1,
        'rock': 1,
        'ghost': 0.5,
        'dragon': 1,
        'dark': 2,
        'steel': 0.5,
        'fairy': 0.5,
    },
    'rock': {
        'normal': 1,
        'fire': 2,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 2,
        'fighting': 0.5,
        'poison': 1,
        'ground': 0.5,
        'flying': 2,
        'psychic': 1,
        'bug': 2,
        'rock': 1,
        'ghost': 1,
        'dragon': 1,
        'dark': 1,
        'steel': 0.5,
        'fairy': 1,
    },
    'ghost': {
        'normal': 0,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 1,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 2,
        'bug': 1,
        'rock': 1,
        'ghost': 2,
        'dragon': 1,
        'dark': 0.5,
        'steel': 1,
        'fairy': 1,
    },
    'dragon': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 1,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 1,
        'ghost': 1,
        'dragon': 2,
        'dark': 1,
        'steel': 0.5,
        'fairy': 0,
    },
    'dark': {
        'normal': 1,
        'fire': 1,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 0.5,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 2,
        'bug': 1,
        'rock': 1,
        'ghost': 2,
        'dragon': 1,
        'dark': 0.5,
        'steel': 1,
        'fairy': 0.5,
    },
    'steel': {
        'normal': 1,
        'fire': 0.5,
        'water': 0.5,
        'electric': 0.5,
        'grass': 1,
        'ice': 2,
        'fighting': 1,
        'poison': 1,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 2,
        'ghost': 1,
        'dragon': 1,
        'dark': 1,
        'steel': 0.5,
        'fairy': 2,
    },
    'fairy': {
        'normal': 1,
        'fire': 0.5,
        'water': 1,
        'electric': 1,
        'grass': 1,
        'ice': 1,
        'fighting': 2,
        'poison': 0.5,
        'ground': 1,
        'flying': 1,
        'psychic': 1,
        'bug': 1,
        'rock': 1,
        'ghost': 1,
        'dragon': 2,
        'dark': 2,
        'steel': 0.5,
        'fairy': 1,
    },
}